baseurl       = "/"
disableKinds  = ["section", "RSS", "sitemap", "robotsTXT"]
googleAnalytics = ""
languageCode = "en-AU"
title         = "Site title here"
uglyurls      = false

[params]
  siteDescription = "Site description here"
  author = ""
  twitterSite = ""
  twitterCreator = ""

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2
